ARG IMAGE_NAME
ARG IMAGE_TAG

FROM $IMAGE_NAME:$IMAGE_TAG

# Install test dependencies
ARG MLMODULE_BUILD_VERSION
RUN pip install  -f /app/dist/ mlmodule[test]==${MLMODULE_BUILD_VERSION:-0.0.dev0}

# Add tests
WORKDIR /app
ADD tests /app/tests
