from mozuma.labels.base import LabelSet

VINVL_LABELS = LabelSet(
    label_set_unique_id="vinvl",
    label_list=[
        "_UNK_",
        "ad",
        "adult",
        "advertisement",
        "air",
        "air conditioner",
        "air vent",
        "aircraft",
        "airplane",
        "airport",
        "alarm clock",
        "alcohol",
        "alley",
        "almond",
        "ambulance",
        "american flag",
        "animal",
        "ankle",
        "antelope",
        "antenna",
        "apartment",
        "apartment building",
        "apple",
        "apple logo",
        "appliance",
        "apron",
        "aquarium",
        "arch",
        "archway",
        "area",
        "area rug",
        "arm",
        "armchair",
        "armrest",
        "arrow",
        "art",
        "artichoke",
        "artwork",
        "asparagus",
        "asphalt",
        "athlete",
        "athletic shoe",
        "audience",
        "avocado",
        "awning",
        "baby",
        "back",
        "back pack",
        "background",
        "backpack",
        "backsplash",
        "backyard",
        "bacon",
        "badge",
        "bag",
        "bagel",
        "baked good",
        "balcony",
        "ball",
        "ball cap",
        "balloon",
        "bamboo",
        "banana",
        "banana bunch",
        "banana peel",
        "banana slice",
        "band",
        "bandage",
        "bandana",
        "bang",
        "bank",
        "banner",
        "bar",
        "bar stool",
        "bark",
        "barn",
        "barrel",
        "barricade",
        "barrier",
        "base",
        "baseball",
        "baseball bat",
        "baseball cap",
        "baseball field",
        "baseball game",
        "baseball glove",
        "baseball mitt",
        "baseball player",
        "baseball players",
        "baseball uniform",
        "baseboard",
        "baseline",
        "basil",
        "basin",
        "basket",
        "bat",
        "bath towel",
        "bath tub",
        "bathing suit",
        "bathroom",
        "bathroom sink",
        "bathtub",
        "batter",
        "battery",
        "beach",
        "beach chair",
        "beach umbrella",
        "bead",
        "beak",
        "beam",
        "bean",
        "beanie",
        "bear",
        "beard",
        "bed",
        "bed frame",
        "bedding",
        "bedroom",
        "bedspread",
        "beef",
        "beer",
        "beer bottle",
        "beet",
        "bell",
        "belt",
        "bench",
        "berry",
        "beverage",
        "bib",
        "bicycle",
        "bicyclist",
        "bike",
        "bike rack",
        "biker",
        "bikini",
        "billboard",
        "bin",
        "binder",
        "bird",
        "bird cage",
        "birthday cake",
        "biscuit",
        "black",
        "blackberry",
        "blade",
        "blanket",
        "blazer",
        "bleacher",
        "blender",
        "blind",
        "block",
        "blood",
        "blossom",
        "blouse",
        "blueberry",
        "board",
        "boardwalk",
        "boat",
        "body",
        "bolt",
        "bone",
        "book",
        "book shelf",
        "bookcase",
        "bookshelf",
        "boot",
        "booth",
        "border",
        "bottle",
        "bottle cap",
        "bottom",
        "boulder",
        "bouquet",
        "bow",
        "bow tie",
        "bowl",
        "box",
        "boy",
        "bracelet",
        "bracket",
        "brake light",
        "branch",
        "bread",
        "breakfast",
        "breast",
        "brick",
        "brick wall",
        "bride",
        "bridge",
        "bridle",
        "briefcase",
        "brim",
        "broccoli",
        "brocolli",
        "broom",
        "brownie",
        "brush",
        "bubble",
        "bucket",
        "buckle",
        "bud",
        "buffalo",
        "bug",
        "building",
        "bull",
        "bumper",
        "bun",
        "bunch",
        "bunny",
        "buoy",
        "burger",
        "burner",
        "bus",
        "bus driver",
        "bus stop",
        "bush",
        "butter",
        "butter knife",
        "butterfly",
        "button",
        "cab",
        "cabbage",
        "cabin",
        "cabinet",
        "cabinet door",
        "cable",
        "caboose",
        "cactus",
        "cafe",
        "cage",
        "cake",
        "calculator",
        "calendar",
        "calf",
        "camera",
        "can",
        "canal",
        "candle",
        "candle holder",
        "candy",
        "cane",
        "canister",
        "canoe",
        "canopy",
        "cap",
        "car",
        "card",
        "cardboard",
        "cardboard box",
        "cargo",
        "carpet",
        "carriage",
        "carrot",
        "cart",
        "carton",
        "case",
        "castle",
        "cat",
        "catcher",
        "catchers mitt",
        "cattle",
        "cauliflower",
        "cd",
        "ceiling",
        "ceiling fan",
        "ceiling light",
        "celery",
        "cell phone",
        "cellphone",
        "cement",
        "cereal",
        "chain",
        "chair",
        "chalkboard",
        "chandelier",
        "character",
        "charger",
        "cheek",
        "cheese",
        "chef",
        "cherry",
        "chest",
        "chicken",
        "child",
        "chili",
        "chimney",
        "chin",
        "chip",
        "chocolate",
        "chopstick",
        "christmas light",
        "christmas tree",
        "church",
        "cigarette",
        "circle",
        "city",
        "classroom",
        "claw",
        "clay",
        "cleat",
        "cliff",
        "clock",
        "clock face",
        "clock hand",
        "clock tower",
        "closet",
        "cloth",
        "clothes",
        "clothing",
        "cloud",
        "coach",
        "coaster",
        "coat",
        "cockpit",
        "coconut",
        "coffee",
        "coffee cup",
        "coffee maker",
        "coffee mug",
        "coffee pot",
        "coffee table",
        "coin",
        "coin slot",
        "coke",
        "collar",
        "column",
        "comb",
        "comforter",
        "computer",
        "computer desk",
        "computer keyboard",
        "computer monitor",
        "computer mouse",
        "computer screen",
        "concrete",
        "condiment",
        "conductor",
        "cone",
        "console",
        "container",
        "control",
        "control panel",
        "controller",
        "cooker",
        "cookie",
        "cooking utensil",
        "cooler",
        "copyright",
        "cord",
        "corn",
        "costume",
        "couch",
        "countertop",
        "couple",
        "court",
        "courtyard",
        "cover",
        "cow",
        "cowboy",
        "cowboy hat",
        "cpu",
        "crab",
        "cracker",
        "crane",
        "crate",
        "cream",
        "croissant",
        "cross",
        "crosswalk",
        "crowd",
        "crown",
        "crumb",
        "crust",
        "cub",
        "cucumber",
        "cuff",
        "cup",
        "cupboard",
        "cupcake",
        "curb",
        "curtain",
        "cushion",
        "customer",
        "cutting board",
        "cycle",
        "cyclist",
        "daisy",
        "dashboard",
        "date",
        "day",
        "decal",
        "deck",
        "decoration",
        "deer",
        "desert",
        "design",
        "desk",
        "desk lamp",
        "dessert",
        "device",
        "dial",
        "diamond",
        "dining room",
        "dining table",
        "dinner",
        "dinosaur",
        "dip",
        "dirt",
        "dirt bike",
        "dirt road",
        "disc",
        "dish",
        "dish soap",
        "dishwasher",
        "dispenser",
        "display",
        "display case",
        "distance",
        "dock",
        "dog",
        "doll",
        "dome",
        "donkey",
        "donut",
        "door",
        "door frame",
        "door handle",
        "door knob",
        "doorknob",
        "doorway",
        "dot",
        "dough",
        "dragon",
        "drain",
        "drape",
        "drawer",
        "drawing",
        "dress",
        "dress shirt",
        "dresser",
        "dressing",
        "drink",
        "driver",
        "driveway",
        "drum",
        "dryer",
        "duck",
        "dugout",
        "dumpster",
        "dvd",
        "dvd player",
        "eagle",
        "ear",
        "earphone",
        "earring",
        "easel",
        "egg",
        "eggplant",
        "elbow",
        "elbow pad",
        "electrical outlet",
        "electronics",
        "elephant",
        "emblem",
        "employee",
        "enclosure",
        "end",
        "end table",
        "engine",
        "engineer",
        "entertainment center",
        "entrance",
        "envelope",
        "exhaust pipe",
        "eye",
        "eyebrow",
        "face",
        "face mask",
        "facial hair",
        "family",
        "fan",
        "farm",
        "father",
        "faucet",
        "feather",
        "feeder",
        "female",
        "fence",
        "fence post",
        "fencing",
        "fender",
        "fern",
        "field",
        "figure",
        "figurine",
        "fin",
        "finger",
        "fingernail",
        "fire",
        "fire escape",
        "fire extinguisher",
        "fire hydrant",
        "fire truck",
        "fireplace",
        "fish",
        "fixture",
        "flag",
        "flame",
        "flamingo",
        "flip flop",
        "floor",
        "floor lamp",
        "flooring",
        "floret",
        "flour",
        "flower",
        "flower pot",
        "foam",
        "fog",
        "foil",
        "folder",
        "folding chair",
        "foliage",
        "food",
        "food truck",
        "foot",
        "foot print",
        "football",
        "footboard",
        "footprint",
        "foreground",
        "forehead",
        "forest",
        "fork",
        "fountain",
        "frame",
        "freezer",
        "french fries",
        "french fry",
        "frisbee",
        "frog",
        "front",
        "front legs",
        "front window",
        "frosting",
        "fruit",
        "fruit stand",
        "fry",
        "fur",
        "furniture",
        "fuselage",
        "gadget",
        "game",
        "game controller",
        "garage",
        "garage door",
        "garbage can",
        "garden",
        "garland",
        "garlic",
        "garment",
        "garnish",
        "gas station",
        "gas tank",
        "gate",
        "gazebo",
        "gazelle",
        "gear",
        "gentleman",
        "gift",
        "giraffe",
        "giraffe head",
        "girl",
        "glass",
        "glass door",
        "glass window",
        "glasses",
        "glaze",
        "globe",
        "glove",
        "goal",
        "goat",
        "goatee",
        "goggles",
        "goose",
        "gown",
        "graffiti",
        "grafitti",
        "grape",
        "grapefruit",
        "grass",
        "grass field",
        "grate",
        "gravel",
        "gravy",
        "green",
        "grill",
        "grinder",
        "groom",
        "ground",
        "group",
        "guard rail",
        "guitar",
        "gun",
        "guy",
        "hair",
        "hair dryer",
        "half",
        "hallway",
        "halter",
        "ham",
        "hamburger",
        "hammer",
        "hand",
        "hand towel",
        "handbag",
        "handle",
        "handle bars",
        "handlebar",
        "hangar",
        "hanger",
        "harbor",
        "harness",
        "hat",
        "hay",
        "head",
        "head band",
        "head light",
        "headband",
        "headboard",
        "headlight",
        "headphone",
        "heart",
        "heater",
        "hedge",
        "heel",
        "helicopter",
        "helmet",
        "herb",
        "herd",
        "highway",
        "hill",
        "hill side",
        "hillside",
        "hilltop",
        "holder",
        "hole",
        "home",
        "home plate",
        "honey",
        "hood",
        "hoodie",
        "hoof",
        "hook",
        "horizon",
        "horn",
        "horse",
        "hose",
        "hot dog",
        "hotel",
        "hotel room",
        "hour hand",
        "house",
        "hubcap",
        "hurdle",
        "hut",
        "ice",
        "ice cream",
        "icing",
        "icon",
        "image",
        "infield",
        "ingredient",
        "inside",
        "instruction",
        "instrument",
        "intersection",
        "iphone",
        "ipod",
        "island",
        "item",
        "ivy",
        "jacket",
        "jar",
        "jean",
        "jeep",
        "jersey",
        "jet",
        "jet engine",
        "jockey",
        "jug",
        "juice",
        "jumpsuit",
        "kayak",
        "ketchup",
        "ketchup bottle",
        "kettle",
        "key",
        "keyboard",
        "keypad",
        "kickstand",
        "kid",
        "kiosk",
        "kitchen",
        "kite",
        "kitten",
        "kitty",
        "kiwi",
        "knee",
        "knee pad",
        "kneepad",
        "knife",
        "knife block",
        "knob",
        "knot",
        "label",
        "ladder",
        "ladle",
        "lady",
        "lake",
        "lamb",
        "lamp",
        "lamp post",
        "lamp shade",
        "lampshade",
        "land",
        "landing gear",
        "landscape",
        "lane",
        "lantern",
        "lanyard",
        "lapel",
        "laptop",
        "laptop computer",
        "latch",
        "lawn",
        "layer",
        "leaf",
        "leash",
        "ledge",
        "leg",
        "legging",
        "lemon",
        "letter",
        "lettering",
        "lettuce",
        "license",
        "license plate",
        "lid",
        "life jacket",
        "life preserver",
        "life vest",
        "lift",
        "light",
        "light bulb",
        "light fixture",
        "light pole",
        "light post",
        "light switch",
        "lighter",
        "lighthouse",
        "limb",
        "lime",
        "line",
        "lion",
        "lip",
        "lipstick",
        "liquid",
        "little girl",
        "living room",
        "lock",
        "locomotive",
        "log",
        "logo",
        "lot",
        "lotion",
        "lounge chair",
        "luggage",
        "luggage cart",
        "lunch",
        "macaroni",
        "machine",
        "magazine",
        "magnet",
        "mailbox",
        "male",
        "man",
        "mane",
        "mango",
        "manhole",
        "manhole cover",
        "mannequin",
        "mantle",
        "map",
        "marina",
        "marker",
        "market",
        "mask",
        "mast",
        "mat",
        "match",
        "mattress",
        "meadow",
        "meal",
        "meat",
        "meatball",
        "median",
        "medicine cabinet",
        "melon",
        "menu",
        "mesh",
        "metal",
        "meter",
        "microphone",
        "microwave",
        "milk",
        "minivan",
        "minute hand",
        "mirror",
        "mitt",
        "mitten",
        "mixer",
        "mixing bowl",
        "money",
        "monitor",
        "monkey",
        "monument",
        "moon",
        "moped",
        "moss",
        "mother",
        "motor",
        "motor bike",
        "motorbike",
        "motorcycle",
        "motorcyclist",
        "mound",
        "mountain",
        "mountain range",
        "mountain side",
        "mountain top",
        "mountainside",
        "mouse",
        "mouse pad",
        "mousepad",
        "moustache",
        "mouth",
        "mozzarella",
        "mud",
        "muffin",
        "muffler",
        "mug",
        "mulch",
        "museum",
        "mushroom",
        "mustache",
        "mustard",
        "muzzle",
        "nail",
        "name",
        "name tag",
        "napkin",
        "neck",
        "neck tie",
        "necklace",
        "necktie",
        "nest",
        "net",
        "netting",
        "newspaper",
        "night",
        "nightstand",
        "noodle",
        "nose",
        "nostril",
        "notebook",
        "notepad",
        "number",
        "numeral",
        "nut",
        "oar",
        "object",
        "obstacle",
        "ocean",
        "ocean water",
        "office",
        "office chair",
        "officer",
        "oil",
        "olive",
        "onion",
        "onion ring",
        "orange",
        "ornament",
        "ostrich",
        "ottoman",
        "outfield",
        "outfit",
        "outlet",
        "outside",
        "oven",
        "oven door",
        "overall",
        "overhang",
        "overpass",
        "owl",
        "ox",
        "pack",
        "package",
        "packet",
        "pad",
        "paddle",
        "page",
        "paint",
        "painting",
        "pajama",
        "palm",
        "palm tree",
        "pan",
        "pancake",
        "panda",
        "pane",
        "panel",
        "pant",
        "paper",
        "paper plate",
        "paper towel",
        "parachute",
        "parade",
        "parasail",
        "parasol",
        "park",
        "park bench",
        "parking lot",
        "parking meter",
        "parking sign",
        "parrot",
        "parsley",
        "passenger",
        "passenger car",
        "passenger train",
        "pasta",
        "pastry",
        "pasture",
        "patch",
        "path",
        "pathway",
        "patio",
        "pavement",
        "paw",
        "pea",
        "peach",
        "peak",
        "peanut",
        "pear",
        "pebble",
        "pedal",
        "pedestrian",
        "peel",
        "pen",
        "pencil",
        "penguin",
        "pepper",
        "pepper shaker",
        "pepperoni",
        "person",
        "petal",
        "phone",
        "photo",
        "photograph",
        "photographer",
        "piano",
        "pickle",
        "pickup truck",
        "picnic table",
        "picture",
        "picture frame",
        "pie",
        "piece",
        "pier",
        "pig",
        "pigeon",
        "pile",
        "pillar",
        "pillow",
        "pillow case",
        "pillowcase",
        "pilot",
        "pin",
        "pine tree",
        "pineapple",
        "pipe",
        "pitcher",
        "pitchers mound",
        "pizza",
        "pizza box",
        "pizza crust",
        "pizza cutter",
        "pizza slice",
        "placemat",
        "plain",
        "plant",
        "plantain",
        "planter",
        "plaque",
        "plastic",
        "plate",
        "platform",
        "platter",
        "player",
        "playground",
        "plug",
        "plumbing",
        "pocket",
        "polar bear",
        "pole",
        "police",
        "police car",
        "police officer",
        "policeman",
        "polo shirt",
        "pond",
        "pony",
        "pony tail",
        "ponytail",
        "pool",
        "porch",
        "portrait",
        "post",
        "poster",
        "pot",
        "potato",
        "pouch",
        "powder",
        "powdered sugar",
        "power line",
        "power pole",
        "price tag",
        "print",
        "printer",
        "produce",
        "product",
        "projector",
        "prong",
        "propeller",
        "puddle",
        "pump",
        "pumpkin",
        "puppy",
        "purse",
        "quilt",
        "rabbit",
        "racer",
        "rack",
        "racket",
        "radiator",
        "radio",
        "radish",
        "raft",
        "rail",
        "railing",
        "railroad",
        "railroad tracks",
        "railway",
        "rain",
        "rainbow",
        "raincoat",
        "raisin",
        "ram",
        "ramp",
        "range",
        "raspberry",
        "receipt",
        "recliner",
        "referee",
        "reflection",
        "reflector",
        "refrigerator",
        "reign",
        "remote",
        "remote control",
        "restaurant",
        "restroom",
        "rib",
        "ribbon",
        "rice",
        "rider",
        "rim",
        "ring",
        "ripple",
        "river",
        "road",
        "roadside",
        "roadway",
        "robe",
        "rock",
        "rock wall",
        "rod",
        "roll",
        "roman numeral",
        "roman numerals",
        "roof",
        "rooftop",
        "room",
        "rope",
        "rose",
        "router",
        "rug",
        "runway",
        "sack",
        "saddle",
        "safety cone",
        "safety jacket",
        "sail",
        "sailboat",
        "salad",
        "salt",
        "salt shaker",
        "sand",
        "sandal",
        "sandwhich",
        "sandwich",
        "satellite dish",
        "sauce",
        "saucer",
        "sausage",
        "scaffolding",
        "scale",
        "scarf",
        "scene",
        "school bus",
        "scissor",
        "scissors",
        "sconce",
        "scooter",
        "scoreboard",
        "screen",
        "screw",
        "sculpture",
        "sea",
        "sea foam",
        "seagull",
        "seal",
        "seasoning",
        "seat",
        "seaweed",
        "second floor",
        "sedan",
        "seed",
        "serving tray",
        "shack",
        "shade",
        "shadow",
        "shaker",
        "shampoo",
        "she",
        "shed",
        "sheep",
        "sheet",
        "shelf",
        "shelter",
        "shield",
        "shin guard",
        "shin guards",
        "shingle",
        "ship",
        "shirt",
        "shoe",
        "shoelace",
        "shop",
        "shopping bag",
        "shore",
        "shoreline",
        "short",
        "shoulder",
        "shovel",
        "shower",
        "shower curtain",
        "shower door",
        "shower head",
        "shrimp",
        "shrub",
        "shutter",
        "side mirror",
        "side table",
        "side window",
        "sidewalk",
        "sign",
        "sign post",
        "signal",
        "signal light",
        "silverware",
        "sink",
        "skate park",
        "skateboard",
        "skateboard ramp",
        "skateboarder",
        "skatepark",
        "skater",
        "ski",
        "ski boot",
        "ski boots",
        "ski goggles",
        "ski jacket",
        "ski lift",
        "ski pants",
        "ski pole",
        "ski poles",
        "ski slope",
        "ski suit",
        "ski tracks",
        "skier",
        "skiier",
        "skiis",
        "skillet",
        "skin",
        "skirt",
        "skull",
        "sky",
        "skylight",
        "skyscraper",
        "slab",
        "slack",
        "slat",
        "sled",
        "sleeve",
        "slice",
        "slope",
        "slot",
        "smartphone",
        "smile",
        "smoke",
        "smoke stack",
        "snack",
        "sneaker",
        "snout",
        "snow",
        "snow board",
        "snow pants",
        "snow suit",
        "snowboard",
        "snowboarder",
        "snowflake",
        "snowman",
        "snowsuit",
        "soap",
        "soap bottle",
        "soap dish",
        "soap dispenser",
        "soccer ball",
        "soccer field",
        "soccer player",
        "sock",
        "socket",
        "soda",
        "soda bottle",
        "soda can",
        "sofa",
        "soil",
        "soldier",
        "soup",
        "spatula",
        "speaker",
        "spear",
        "spectator",
        "spice",
        "spinach",
        "spire",
        "splash",
        "spoke",
        "sponge",
        "spoon",
        "spot",
        "spray",
        "spray bottle",
        "sprinkle",
        "squash",
        "stabilizer",
        "stack",
        "stadium",
        "stage",
        "stain",
        "stair",
        "staircase",
        "stairway",
        "stall",
        "stand",
        "stapler",
        "star",
        "station",
        "station wagon",
        "statue",
        "steak",
        "steam",
        "steeple",
        "steering wheel",
        "stem",
        "step",
        "stereo",
        "stick",
        "sticker",
        "stone",
        "stone wall",
        "stool",
        "stop",
        "stop light",
        "stop sign",
        "stoplight",
        "store",
        "storefront",
        "stove",
        "stove top",
        "strap",
        "straw",
        "strawberry",
        "stream",
        "streamer",
        "street",
        "street lamp",
        "street light",
        "street sign",
        "string",
        "strip",
        "stripe",
        "stroller",
        "structure",
        "student",
        "stuffed animal",
        "stuffed bear",
        "stump",
        "sugar",
        "suit",
        "suit jacket",
        "suitcase",
        "sun",
        "sunflower",
        "sunglasses",
        "sunset",
        "surf",
        "surface",
        "surfboard",
        "surfer",
        "surfing",
        "suspender",
        "suv",
        "swan",
        "sweat band",
        "sweatband",
        "sweater",
        "sweatpants",
        "sweatshirt",
        "sweet potato",
        "swim trunks",
        "swimming pool",
        "swimsuit",
        "switch",
        "sword",
        "symbol",
        "syrup",
        "table",
        "table cloth",
        "table lamp",
        "tablecloth",
        "tablet",
        "tabletop",
        "tag",
        "tail",
        "tail feathers",
        "tail fin",
        "tail light",
        "tail lights",
        "tail wing",
        "tangerine",
        "tank",
        "tank top",
        "tap",
        "tape",
        "tarmac",
        "tarp",
        "tattoo",
        "taxi",
        "taxi cab",
        "tea",
        "tea kettle",
        "tea pot",
        "team",
        "teapot",
        "teddy",
        "teddy bear",
        "tee shirt",
        "teeth",
        "telephone",
        "telephone pole",
        "television",
        "tennis",
        "tennis ball",
        "tennis court",
        "tennis match",
        "tennis net",
        "tennis player",
        "tennis racket",
        "tennis shoe",
        "tent",
        "terminal",
        "text",
        "throw pillow",
        "thumb",
        "tie",
        "tiger",
        "tights",
        "tile",
        "tile floor",
        "tine",
        "tire",
        "tissue",
        "tissue box",
        "toast",
        "toaster",
        "toaster oven",
        "toddler",
        "toe",
        "tofu",
        "toilet",
        "toilet bowl",
        "toilet brush",
        "toilet lid",
        "toilet paper",
        "toilet seat",
        "toilet tank",
        "toiletry",
        "tomato",
        "tomato sauce",
        "tomato slice",
        "tongs",
        "tongue",
        "tool",
        "toothbrush",
        "toothpaste",
        "toothpick",
        "top",
        "topping",
        "tortilla",
        "touchpad",
        "tourist",
        "towel",
        "towel rack",
        "tower",
        "town",
        "toy",
        "track",
        "tractor",
        "traffic",
        "traffic cone",
        "traffic light",
        "traffic sign",
        "traffic signal",
        "trail",
        "trailer",
        "train",
        "train car",
        "train cars",
        "train engine",
        "train front",
        "train platform",
        "train station",
        "train track",
        "train tracks",
        "trash",
        "trash bag",
        "trash bin",
        "trash can",
        "trashcan",
        "tray",
        "tree",
        "tree branch",
        "tree leaves",
        "tree line",
        "tree trunk",
        "triangle",
        "trick",
        "tripod",
        "trolley",
        "trough",
        "trousers",
        "truck",
        "trunk",
        "tshirt",
        "tub",
        "tube",
        "tulip",
        "tunnel",
        "turbine",
        "turf",
        "turkey",
        "tusk",
        "tv stand",
        "twig",
        "umbrella",
        "umpire",
        "undershirt",
        "underwear",
        "uniform",
        "urinal",
        "urn",
        "utensil",
        "utility pole",
        "valley",
        "van",
        "vane",
        "vanity",
        "vase",
        "vegetable",
        "veggie",
        "vehicle",
        "vending machine",
        "vent",
        "vest",
        "video camera",
        "video game",
        "view",
        "village",
        "vine",
        "visor",
        "wagon",
        "waist",
        "wake",
        "walkway",
        "wall",
        "wallet",
        "wallpaper",
        "walnut",
        "washer",
        "washing machine",
        "waste basket",
        "watch",
        "water",
        "water bottle",
        "water tank",
        "waterfall",
        "watermark",
        "watermelon",
        "wave",
        "weather",
        "weather vane",
        "website",
        "weed",
        "wet suit",
        "wetsuit",
        "wheel",
        "wheelchair",
        "whipped cream",
        "whisk",
        "whisker",
        "whiteboard",
        "wig",
        "wii",
        "wii controller",
        "wii remote",
        "wild",
        "wildflower",
        "window",
        "window frame",
        "window sill",
        "windowsill",
        "windshield",
        "windshield wiper",
        "windshield wipers",
        "wine",
        "wine bottle",
        "wing",
        "wiper",
        "wire",
        "wire fence",
        "woman",
        "wood",
        "wool",
        "word",
        "worker",
        "wrapper",
        "wrist",
        "wrist band",
        "wrist watch",
        "wristband",
        "wristwatch",
        "writing",
        "yacht",
        "yard",
        "yellow",
        "yogurt",
        "yolk",
        "young man",
        "zebra",
        "zipper",
        "zoo",
        "zucchini",
    ],
)
