FROM nvidia/cuda:11.0-runtime-ubuntu20.04

# Download Miniconda py37 - https://docs.conda.io/en/latest/miniconda.html#linux-installers
RUN apt-get -qq update && apt-get -qq -y install curl bzip2 git build-essential \
    && curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh

ENV PATH /opt/conda/bin:$PATH

ARG PYTHON_VERSION=3.7.10
ARG CUDA_VERSION=11.0
ARG TORCH_VERSION=1.7.1
ARG TORCHVISION_VERSION=0.8.2
RUN conda create -n app python=$PYTHON_VERSION cudatoolkit=$CUDA_VERSION \
      pytorch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} -c pytorch \
      && conda run -n app --no-capture-output pip install \
        mmcv-full==1.3.1 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html \
        git+https://github.com/openai/CLIP.git@8cad3a736a833bc4c9b4dd34ef12b52ec0e68856 \
        git+https://github.com/open-mmlab/mmdetection.git@2894516bacf9ff82c3bc6d6970019d0890a993aa \
        facenet-pytorch==2.5.2

# Make sure the shell commands run inside the environment
SHELL ["conda", "run", "-n", "app", "--no-capture-output", "/bin/bash", "-c"]
